spring:
  application:
    name: tango-songs
  jpa:
    database-platform: com.example.tangosongs.configuration.CustomPostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/tango_songs
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  security:
    oauth2:
      client:
        provider:
          spotify:
            token-uri: "https://accounts.spotify.com/api/token"
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic

feign:
  client:
    config:
      spotify:
        url: https://api.spotify.com
