spring:
  application:
    name: tango-songs
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        provider:
          spotify:
            token-uri: "https://accounts.spotify.com/api/token"
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic

feign:
  client:
    config:
      spotify:
        url: https://api.spotify.com
